version: "3.0"
services:
  app:
    build: .
    ports:
      - 80:3000
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  dummy:
    image: nginx:alpine

  ruby:
    image: ruby:alpine
    command: |
      sh -c "
      ruby <<'EOF'
        require 'bundler/inline'

        gemfile do
          source 'https://rubygems.org'

          gem 'webrick'
        end

        server = WEBrick::HTTPServer.new(:BindAddress => '0.0.0.0', :Port => 3000)
        server.mount_proc('/') do |req, res|
          res.body = 'Hello World'
          res.status = 200
        end
        server.start
      EOF
      "
